name: mcid_connect
description: "A Dart package for Minecraft authentication that simplifies the process of logging into Minecraft services using Microsoft accounts."
version: 0.0.6
homepage: https://www.karasu256.com
repository: https://github.com/Karasu-Lab/mcid_connect

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dotenv: ^4.2.0
  envied: ^1.1.1
  flutter:
    sdk: flutter
  http: ^1.4.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
